---
- debug: var=hostvars['hostname']
- debug: var=hostvars['fqdn']
- debug: var=hostvars['ansible_local']
- debug: var=hostvars['ansible_playbook_python']
- debug: var=hostvars['inventory_hostname']
- debug: var=hostvars['inventory_file']
- debug: var=hostvars['groups']
- name: upgrade all packages
  become: yes
  yum:
    name: "*"
    state: latest
- name: install zsh
  become: yes
  yum:
    name: "zsh"
    state: latest
- name: install the 'Development tools' package group
  yum:
    name: "@Development tools"
    state: present
- name: install python-devel
  become: yes
  yum:
    name: "python-devel"
    state: present
- name: install atlas-sse3-devel
  become: yes
  yum:
    name: "atlas-sse3-devel"
    state: present
- name: install lapack-devel
  become: yes
  yum:
    name: "lapack-devel"
    state: present
- name: install mysql-devel
  become: yes
  yum:
    name: "mysql-devel"
    state: latest
- name: install npm
  become: yes
  yum:
    name: "npm"
    state: latest
- name: generate ssh key pair
  command: 'ssh-keygen -q -t rsa -f /home/{{ ansible_user_id }}/.ssh/id_rsa -C "" -N ""'
  args:
    creates: "/home/{{ ansible_user_id }}/.ssh/id_rsa"
- name: Read SSH public key to authorize
  shell: "cat /home/{{ ansible_user_id }}/.ssh/id_rsa.pub"
  register: ssh_pub_key
- name: Authorize key with GitHub
  local_action:
    module: github_key
    name: Cloud9-Dev
    token: "{{ github_personal_access_token }}"
    pubkey: "{{ ssh_pub_key.stdout }}"
- name: configure git client
  template:
    src: gitconfig.j2
    dest: "/home/{{ ansible_user_id }}/.gitconfig"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0644
- name: clone github repos
  git:
    repo: "{{ item.repo }}"
    dest: "/home/{{ ansible_user_id }}/github/{{ item.dir_name }}"
    accept_hostkey: yes
  loop: "{{ github_repos }}"
- name: install Oh-my-zsh
  shell: 'sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"'
- name: configure Oh-my-zsh
  template:
    src: zshrc.j2
    dest: "/home/{{ ansible_user_id }}/.zshrc"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0644
- name: install pyenv
  shell: 'curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash'
- name: switch to zsh
  shell: 'zsh'
- name: install python
  shell: 'pyenv install 3.6.9'
- name: setup python global environment
  shell: 'pyenv global 3.6.9'
